export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';
export const CUSTOMER_CLEAR_ERRORS = 'CUSTOMER_CLEAR_ERRORS'
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL'